#!/bin/sh
if [ "$1" = "delete" ]
then
	git branch --merged | grep -v "\*"  | grep -v master | xargs -n 1 git branch -d
else
	git branch --merged | grep -v "\*" | grep -v master 
	echo "use '$0 delete' to delete the branches"
fi
