#!/bin/bash

#PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
PROJECT='/home/josh/workcode/salt'
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? -ne 0 ]; then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "X$FILES" != "X" ]; then
    echo "Running Code Sniffer..."
    ./vendor/bin/phpcs --encoding=utf-8 -n -p $FILES
    if [ $? -ne 0 ]; then
        echo "WTF --- Error $?"
        echo "Coding standards errors have been detected. Running phpcbf..."
        ./vendor/bin/phpcbf --encoding=utf-8 -n -p $FILES
        git add $FILES
        echo "Running Code Sniffer again..."
        ./vendor/bin/phpcs --encoding=utf-8 -n -p $FILES
        if [ $? -ne 0 ]; then
            echo "Errors found not fixable automatically"
            exit 1
        fi
    fi
fi
