#!/bin/bash

# Maim version
maim -s | xclip -selection clipboard -target image/png

# Scrot version
# scrot -s /tmp/foo.png
# xclip -selection clipboard -t image/png -i /tmp/foo.png
# rm /tmp/foo.png
