#!/bin/sh

# do click stuff
case $BLOCK_BUTTON in
	#left click
	1) ;;
	#middle click
	2) ;;
	#right click
	3) ;;
	#scroll up
	4) ;; 
	#scroll down
	5) ;; 
	#shift left click
	6) setsid "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

packages=$(yay -Syu -p | wc -l)
num=$(expr $packages - 5)

echo "📦$num"
